version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps"

  - package-ecosystem: "npm"
    directory: "/dl-landing"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps"

  - package-ecosystem: "npm"
    directory: "/dl-tierlist"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps"

  - package-ecosystem: "npm"
    directory: "/dl-patch"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps"

  - package-ecosystem: "npm"
    directory: "/dl-activity"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps"

  - package-ecosystem: "npm"
    directory: "/builds/frontend"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps"

  - package-ecosystem: "npm"
    directory: "/builds/backend"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps"
